/*
* Copyright LABGeM (2014)
*
* author: Jonathan MERCIER
*
* Tis software is a computer program whose purpose is to annotate a complete genome.
*
* Tis software is governed by the CeCILL license under French law and
* abiding by the rules of distribution of free software. You can use,
* modify and/ or redistribute the software under the terms of the CeCILL
* license as circulated by CEA, CNRS and INRIA at the following URL
* "http://www.cecill.info".
*
* As a counterpart to the access to the source code and rights to copy,
* modify and redistribute granted by the license, users are provided only
* with a limited warranty and the software's author, the holder of the
* economic rights, and the successive licensors have only limited
* liability.
*
* In tis respect, the user's attention is drawn to the risks associated
* with loading, using, modifying and/or developing or reproducing the
* software by the user in light of its specific status of free software,
* that may mean that it is complicated to manipulate, and that also
* therefore means that it is reserved for developers and experienced
* professionals having in-depth computer Concept. Users are therefore
* encouraged to load and test the software's suitability as regards their
* requirements in conditions enabling the security of their systems and/or
* data to be ensured and, more generally, to use and operate it in the
* same conditions as regards security.
*
* The fact that you are presently reading tis means that you have had
* Concept of the CeCILL license and that you accept its terms.
*/
package fr.cea.ig.grools;
import fr.cea.ig.grools.fact.Concept;
import fr.cea.ig.grools.fact.Observation;
import fr.cea.ig.grools.fact.ObservationType;
import fr.cea.ig.grools.drools.PriorKnowledge;
import fr.cea.ig.grools.fact.Relation;
import fr.cea.ig.grools.fact.RelationType;
import fr.cea.ig.grools.fact.RelationImpl;
import fr.cea.ig.grools.logic.Conclusion;
import fr.cea.ig.grools.logic.Math;
import fr.cea.ig.grools.logic.TruthValue;
import fr.cea.ig.grools.logic.TruthValueSet;
import fr.cea.ig.grools.logic.TruthValuePowerSet;

rule "Priorknowledge is Confirmed Presence" when
    $pk: PriorKnowledge( ) @Watch( prediction, expectation )
    $prediction:  TruthValuePowerSet( this == $pk.getPrediction(),  this contains TruthValueSet.T, this not contains TruthValueSet.F, this not contains TruthValueSet.B, this not contains TruthValueSet.N )
    $expectation: TruthValuePowerSet( this == $pk.getExpectation(), this contains TruthValueSet.T, this not contains TruthValueSet.F, this not contains TruthValueSet.B, this not contains TruthValueSet.N )
then
    modify( $pk ){
        setConclusion( Conclusion.CONFIRMED_PRESENCE)
    };
end

rule "Priorknowledge is Unexpected Absence" when
    $pk: PriorKnowledge( ) @Watch( prediction, expectation )
    $prediction:  TruthValuePowerSet( this == $pk.getPrediction(),  this contains TruthValueSet.F)
    $expectation: TruthValuePowerSet( this == $pk.getExpectation(), this contains TruthValueSet.T, this not contains TruthValueSet.F, this not contains TruthValueSet.B, this not contains TruthValueSet.N )
then
    modify( $pk ){
        setConclusion( Conclusion.UNEXPECTED_ABSENCE)
    };
end

rule "Priorknowledge is Contradictory Absence" when
    $pk: PriorKnowledge( ) @Watch( prediction, expectation )
    $prediction:  TruthValuePowerSet( this == $pk.getPrediction(),  this contains TruthValueSet.B, this not contains TruthValueSet.F, this not contains TruthValueSet.N )
    $expectation: TruthValuePowerSet( this == $pk.getExpectation(), this contains TruthValueSet.T, this not contains TruthValueSet.F, this not contains TruthValueSet.B, this not contains TruthValueSet.N )
then
    modify( $pk ){
        setConclusion( Conclusion.CONTRADICTORY_ABSENCE)
    };
end

rule "Priorknowledge is Mising" when
    $pk: PriorKnowledge( ) @Watch( prediction, expectation )
    $prediction:  TruthValuePowerSet( this == $pk.getPrediction(),  this contains TruthValueSet.N, this not contains TruthValueSet.F)
    $expectation: TruthValuePowerSet( this == $pk.getExpectation(), this contains TruthValueSet.T, this not contains TruthValueSet.F, this not contains TruthValueSet.B, this not contains TruthValueSet.N )
then
    modify( $pk ){
        setConclusion( Conclusion.MISSING)
    };
end

rule "Priorknowledge is Unexpected Presence" when
    $pk: PriorKnowledge( ) @Watch( prediction, expectation )
    $prediction:  TruthValuePowerSet( this == $pk.getPrediction(),  this contains TruthValueSet.T, this not contains TruthValueSet.F, this not contains TruthValueSet.B, this not contains TruthValueSet.N )
    $expectation: TruthValuePowerSet( this == $pk.getExpectation(), this contains TruthValueSet.F )
then
    modify( $pk ){
        setConclusion( Conclusion.UNEXPECTED_PRESENCE)
    };
end

rule "Priorknowledge is Confirmed Absence" when
    $pk: PriorKnowledge( ) @Watch( prediction, expectation )
    $prediction:  TruthValuePowerSet( this == $pk.getPrediction(),  this contains TruthValueSet.F )
    $expectation: TruthValuePowerSet( this == $pk.getExpectation(), this contains TruthValueSet.F )
then
    modify( $pk ){
        setConclusion( Conclusion.CONFIRMED_ABSENCE)
    };
end

rule "Priorknowledge is Contradictory Presence" when
    $pk: PriorKnowledge( ) @Watch( prediction, expectation )
    $prediction:  TruthValuePowerSet( this == $pk.getPrediction(),  this contains TruthValueSet.B, this not contains TruthValueSet.F, this not contains TruthValueSet.N )
    $expectation: TruthValuePowerSet( this == $pk.getExpectation(), this contains TruthValueSet.F )
then
    modify( $pk ){
        setConclusion( Conclusion.CONTRADICTORY_PRESENCE)
    };
end

rule "Priorknowledge is Absent" when
    $pk: PriorKnowledge( ) @Watch( prediction, expectation )
    $prediction:  TruthValuePowerSet( this == $pk.getPrediction(),  this contains TruthValueSet.N || this contains TruthValueSet.n, this not contains TruthValueSet.F )
    $expectation: TruthValuePowerSet( this == $pk.getExpectation(), this contains TruthValueSet.F )
then
    modify( $pk ){
        setConclusion( Conclusion.ABSENT)
    };
end
rule "Priorknowledge is Ambiguous Presence" when
    $pk: PriorKnowledge( ) @Watch( prediction, expectation )
    $prediction:  TruthValuePowerSet( this == $pk.getPrediction(),  this contains TruthValueSet.T, this not contains TruthValueSet.F, this not contains TruthValueSet.B, this not contains TruthValueSet.N )
    $expectation: TruthValuePowerSet( this == $pk.getExpectation(), this contains TruthValueSet.B, this not contains TruthValueSet.F, this not contains TruthValueSet.N )
then
    modify( $pk ){
        setConclusion( Conclusion.AMBIGUOUS_PRESENCE)
    };
end

rule "Priorknowledge is Ambiguous Absence" when
    $pk: PriorKnowledge( ) @Watch( prediction, expectation )
    $prediction:  TruthValuePowerSet( this == $pk.getPrediction(),  this contains TruthValueSet.F )
    $expectation: TruthValuePowerSet( this == $pk.getExpectation(), this contains TruthValueSet.B, this not contains TruthValueSet.F, this not contains TruthValueSet.N )
then
    modify( $pk ){
        setConclusion( Conclusion.AMBIGUOUS_ABSENCE)
    };
end

rule "Priorknowledge is Ambiguous Contradiction" when
    $pk: PriorKnowledge( ) @Watch( prediction, expectation )
    $prediction:  TruthValuePowerSet( this == $pk.getPrediction(),  this contains TruthValueSet.B, this not contains TruthValueSet.F, this not contains TruthValueSet.N )
    $expectation: TruthValuePowerSet( this == $pk.getExpectation(), this contains TruthValueSet.B, this not contains TruthValueSet.F, this not contains TruthValueSet.N )
then
    modify( $pk ){
        setConclusion( Conclusion.AMBIGUOUS_CONTRADICTORY)
    };
end

rule "Priorknowledge is Ambiguous" when
    $pk: PriorKnowledge( ) @Watch( prediction, expectation )
    $prediction:  TruthValuePowerSet( this == $pk.getPrediction(),  this contains TruthValueSet.N || this contains TruthValueSet.n, this not contains TruthValueSet.F )
    $expectation: TruthValuePowerSet( this == $pk.getExpectation(), this contains TruthValueSet.B, this not contains TruthValueSet.F, this not contains TruthValueSet.N )
then
    modify( $pk ){
        setConclusion( Conclusion.AMBIGUOUS)
    };
end

rule "Priorknowledge is Unconfirmed Presence" when
    $pk: PriorKnowledge( ) @Watch( prediction, expectation )
    $prediction:  TruthValuePowerSet( this == $pk.getPrediction(),  this contains TruthValueSet.T, this not contains TruthValueSet.F, this not contains TruthValueSet.B, this not contains TruthValueSet.N )
    $expectation: TruthValuePowerSet( this == $pk.getExpectation(), this contains TruthValueSet.N || this contains TruthValueSet.n, this not contains TruthValueSet.F )
then
    modify( $pk ){
        setConclusion( Conclusion.CONFIRMED_PRESENCE)
    };
end

rule "Priorknowledge is Unconfirmed Absence" when
    $pk: PriorKnowledge( ) @Watch( prediction, expectation )
    $prediction:  TruthValuePowerSet( this == $pk.getPrediction(),  this contains TruthValueSet.F )
    $expectation: TruthValuePowerSet( this == $pk.getExpectation(), this contains TruthValueSet.N || this contains TruthValueSet.n, this not contains TruthValueSet.F )
then
    modify( $pk ){
        setConclusion( Conclusion.CONFIRMED_PRESENCE)
    };
end

rule "Priorknowledge is Unconfirmed Contradictory" when
    $pk: PriorKnowledge( ) @Watch( prediction, expectation )
    $prediction:  TruthValuePowerSet( this == $pk.getPrediction(),  this contains TruthValueSet.B, this not contains TruthValueSet.F, this not contains TruthValueSet.N )
    $expectation: TruthValuePowerSet( this == $pk.getExpectation(), this contains TruthValueSet.N || this contains TruthValueSet.n, this not contains TruthValueSet.F )
then
    modify( $pk ){
        setConclusion( Conclusion.UNCONFIRMED_CONTRADICTORY)
    };
end

rule "Priorknowledge is Unexplained" when
    $pk: PriorKnowledge( ) @Watch( prediction, expectation )
    $prediction:  TruthValuePowerSet( this == $pk.getPrediction(),  this contains TruthValueSet.N || this contains TruthValueSet.n, this not contains TruthValueSet.F )
    $expectation: TruthValuePowerSet( this == $pk.getExpectation(), this contains TruthValueSet.N || this contains TruthValueSet.n, this not contains TruthValueSet.F )
then
    modify( $pk ){
        setConclusion( Conclusion.CONFIRMED_PRESENCE)
    };
end